### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by w00p** [LGLabGreg/Koindash#19]
Hi,

Nice project :) 

do you have a short install instruction? 
What files and api keys need to be changed?

I have done the following:
1. git clone
2. npm install
3. changed info in firebase.js
4. npm start

Is starts, bit i get the following error popping up: 
`currencies.js:60 Uncaught TypeError: Cannot read property 'expiry' of null`

**Comment by LGLabGreg** [comment]
Hi,

This is a personal project and is not really ready to be installed by 3rd parties. You can find a usable version online: https://koindash.com/
